apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sql-server
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default # Azure example
  volumeMode: Filesystem