apiVersion: v1
kind: Service
metadata:
  namespace: sql-server
  name: mssql
  annotations:
    app: mssql
  labels:
    app: mssql
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.0.226
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: mssql
